# Generated by Django 3.2.7 on 2021-10-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16, null=True)),
                ('set_meal', models.CharField(max_length=16, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '未启用'), (1, '生效中'), (2, '已封禁')], default=0)),
                ('available_till', models.DateTimeField()),
                ('task_num_left', models.SmallIntegerField(default=3)),
                ('comment_num_left', models.IntegerField(default=0)),
                ('peer_num_left', models.IntegerField(default=3)),
                ('email', models.CharField(max_length=20, null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16, null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
