# Generated by Django 3.2.7 on 2021-10-12 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('base', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('base', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='delegate',
            managers=[
                ('base', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='customer',
            name='Delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DYAdmin.delegate'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='available_till',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='comment_num_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delegate',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未启用'), (1, '生效中'), (2, '已封禁')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CustomerLoginLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('browser', models.CharField(max_length=80)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('base', django.db.models.manager.Manager()),
            ],
        ),
    ]
