# Generated by Django 3.2.7 on 2021-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0002_auto_20211012_1152'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customerloginlogging',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='delegate',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='delegate',
            name='available_till',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='comment_num_left',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='remark',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
