# Generated by Django 3.2.7 on 2021-10-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0003_auto_20211014_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customerloginlogging',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='delegate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='available_till',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comment_num_left',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='peer_num_left',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='task_num_left',
            field=models.SmallIntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
