# Generated by Django 3.2.7 on 2021-10-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0005_myhotword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.CharField(max_length=16, null=True)),
                ('unique_id', models.CharField(max_length=16, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('avatar_thumb', models.URLField(max_length=150, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('type', models.SmallIntegerField(null=True, verbose_name='1 个人 2 企业')),
                ('company', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('remark', models.CharField(max_length=30, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, null=True)),
                ('within_days', models.CharField(max_length=150, null=True)),
                ('filter_words', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('aweme_id', models.CharField(max_length=16, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('cover', models.CharField(max_length=255, null=True)),
                ('like_num', models.IntegerField(null=True)),
                ('comment_num', models.IntegerField(null=True)),
                ('download_num', models.IntegerField(null=True)),
                ('share_num', models.IntegerField(null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.task')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.CharField(max_length=16, null=True)),
                ('unique_id', models.CharField(max_length=16, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('avatar_thumb', models.URLField(max_length=150, null=True)),
                ('follower_count', models.IntegerField(null=True)),
                ('total_favorited', models.IntegerField(null=True)),
                ('custom_verify', models.CharField(max_length=50, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('follow_up_person', models.CharField(max_length=10, null=True)),
                ('content', models.CharField(max_length=40, null=True)),
                ('remark', models.CharField(max_length=30, null=True)),
                ('Consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.consumer')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.CharField(max_length=16, null=True)),
                ('unique_id', models.CharField(max_length=16, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('avatar_thumb', models.URLField(max_length=150, null=True)),
                ('like_num', models.IntegerField(null=True)),
                ('vx', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('hit_word', models.CharField(max_length=20, null=True)),
                ('status', models.SmallIntegerField(null=True, verbose_name='0 未处理 1 已处理')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.task')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.video')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
