# Generated by Django 3.2.7 on 2021-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0006_comment_consumer_followup_peer_task_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='sec_uid',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
