# Generated by Django 3.2.7 on 2021-10-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0007_peer_sec_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='peer_monitor_ids',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='filter_words',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='within_days',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PeerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('aweme_id', models.CharField(max_length=16, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.customer')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.task')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
