# Generated by Django 3.2.7 on 2021-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0008_auto_20211026_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
