# Generated by Django 3.2.7 on 2021-10-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0009_auto_20211026_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='peervideo',
            name='desc',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
