# Generated by Django 3.2.7 on 2021-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0010_peervideo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uid',
        ),
        migrations.AddField(
            model_name='comment',
            name='sec_uid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar_thumb',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
