# Generated by Django 3.2.7 on 2021-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0011_auto_20211027_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Task',
        ),
        migrations.AddField(
            model_name='video',
            name='Tasks',
            field=models.ManyToManyField(to='DYAdmin.Task'),
        ),
    ]
