# Generated by Django 3.2.7 on 2021-10-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0014_auto_20211028_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='peervideo',
            name='Peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DYAdmin.peer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DYAdmin.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DYAdmin.video'),
        ),
    ]
