# Generated by Django 3.2.7 on 2021-10-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0016_auto_20211029_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='uid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
