# Generated by Django 3.2.7 on 2021-10-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0017_auto_20211029_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vx',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
