# Generated by Django 3.2.7 on 2021-10-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0018_auto_20211029_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='0 未处理 1 已处理'),
        ),
    ]
