# Generated by Django 3.2.7 on 2021-10-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0019_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_ai',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='0 普通评论 1 智能推荐'),
        ),
        migrations.AlterField(
            model_name='peervideo',
            name='comment_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
