# Generated by Django 3.2.7 on 2021-10-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0020_auto_20211029_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peervideo',
            name='aweme_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
