# Generated by Django 3.2.7 on 2021-10-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0021_alter_peervideo_aweme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='PeerVideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DYAdmin.peervideo'),
        ),
    ]
