# Generated by Django 3.2.7 on 2021-10-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0022_comment_peervideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='consumer',
            name='sec_uid',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='nickname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='uid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
