# Generated by Django 3.2.7 on 2021-10-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0024_alter_comment_vx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
