# Generated by Django 3.2.7 on 2021-11-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0026_auto_20211101_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
