# Generated by Django 3.2.7 on 2021-11-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0027_alter_consumer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
