# Generated by Django 3.2.7 on 2021-11-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0030_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.CharField(max_length=455, null=True),
        ),
    ]
