# Generated by Django 3.2.7 on 2021-12-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DYAdmin', '0032_auto_20211107_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='short_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
